/**
 * Exports the base configuration created by `prisma db seed` (countries,
 * cities, categories, genres, plans, discovery sources) as idempotent SQL
 * for the desktop app. Foreign keys are resolved by natural keys (country
 * code, city slug) so the file also applies to databases created elsewhere.
 *   DATABASE_URL=… npx tsx scripts/export-base-data.mts > base-data.sql
 */
import { PrismaClient } from "@prisma/client";

const db = new PrismaClient();

function lit(v: unknown): string {
  if (v === null || v === undefined) return "NULL";
  if (typeof v === "number") return Number.isFinite(v) ? String(v) : "NULL";
  if (typeof v === "boolean") return v ? "TRUE" : "FALSE";
  if (v instanceof Date) return `'${v.toISOString()}'`;
  if (Array.isArray(v)) return v.length ? `ARRAY[${v.map(lit).join(", ")}]` : "'{}'";
  if (typeof v === "object") return `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`;
  return `'${String(v).replace(/'/g, "''")}'`;
}

type Row = Record<string, unknown>;
const FK: Record<string, (row: Row) => string> = {
  countryId: (r) => `(SELECT "id" FROM "Country" WHERE "code" = ${lit(r.__countryCode)})`,
  cityId: (r) => `(SELECT "id" FROM "City" WHERE "slug" = ${lit(r.__citySlug)})`,
};

async function table(name: string, sql: string, out: string[]) {
  const rows = await db.$queryRawUnsafe<Row[]>(sql);
  for (const r of rows) {
    const cols = Object.keys(r).filter((c) => !c.startsWith("__"));
    const values = cols.map((c) => (FK[c] ? FK[c](r) : c === "venueId" ? "NULL" : lit(r[c])));
    out.push(`INSERT INTO "${name}" (${cols.map((c) => `"${c}"`).join(", ")}) VALUES (${values.join(", ")}) ON CONFLICT DO NOTHING;`);
  }
}

const out = ["-- ORIVEXY NIGHTS base data (generated by scripts/export-base-data.mts). Idempotent.", "BEGIN;"];
await table("Country", `SELECT * FROM "Country" ORDER BY "code"`, out);
await table("City", `SELECT c.*, co."code" AS "__countryCode" FROM "City" c JOIN "Country" co ON co."id" = c."countryId" ORDER BY c."slug"`, out);
await table("Category", `SELECT * FROM "Category" ORDER BY "order"`, out);
await table("MusicGenre", `SELECT * FROM "MusicGenre" ORDER BY "order"`, out);
await table("Plan", `SELECT * FROM "Plan" ORDER BY "code"`, out);
await table(
  "DiscoverySource",
  `SELECT s."id", s."key", s."name", s."type"::text AS "type", s."enabled", s."url", s."cityId", s."trust"::text AS "trust", s."autoPublish", s."allowImages",
          s."deactivateMissing", s."syncIntervalMin", s."config", now() AS "createdAt", now() AS "updatedAt", c."slug" AS "__citySlug"
     FROM "DiscoverySource" s JOIN "City" c ON c."id" = s."cityId" ORDER BY s."key"`,
  out,
);
out.push("COMMIT;");
console.log(out.join("\n"));
await db.$disconnect();
